In [1]:
# Import 
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

import sys
sys.path.append('../')
from helpers import cm2inch, title, show_num_contours, load_datasets
from melodic_contour import *
matplotlib.style.use('styles.mplstyle')

In [2]:
dfs, contours = load_datasets(normalize=False)

In [3]:
contours['erk']

array([[69., 69., 69., ..., 69., 69., 69.],
       [67., 67., 67., ..., 65., 65., 65.],
       [69., 69., 69., ..., 69., 69., 69.],
       ...,
       [69., 69., 69., ..., 67., 67., 67.],
       [60., 60., 60., ..., 67., 67., 67.],
       [69., 69., 69., ..., 71., 71., 71.]])

In [37]:
x = np.array([[1, 0, -1, 2, 4, 0], [1, 0, -1, 2, 5, 1]])
x

array([[ 1,  0, -1,  2,  4,  0],
       [ 1,  0, -1,  2,  5,  1]])

In [51]:
x_cur  = x[:, 1:-1]
x_prev = x[:, :-2]
x_next = x[:, 2:]

slope = 1/2 * ((x_cur - x_prev) + (x_next - x_prev)/2)
slope

array([[-1.  ,  0.  ,  2.75,  0.5 ],
       [-1.  ,  0.  ,  3.  ,  1.25]])

In [53]:
x_cur - x_prev

array([[-1, -1,  3,  2],
       [-1, -1,  3,  3]])

In [54]:
(x_next - x_prev) / 2

array([[-1. ,  1. ,  2.5, -1. ],
       [-1. ,  1. ,  3. , -0.5]])

In [38]:
slopes = x[1:] - x[:-1]

In [39]:
x_cur = x[1:-1]
x_prev = x[:-2]
x_next = x[2:]
x_cur, x_prev, x_next

(array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64),
 array([], shape=(0, 6), dtype=int64))

In [34]:
d_prev_cur = x_cur - x_prev
d_prev_next = (x_next - x_cur) / 2
slope = 1/2 * (d_prev_cur + d_prev_next)
d = [slope[0]] + slope.tolist() + [slope[-1]]
d

[-0.75, -0.75, 0.25, 2.0, 0.0, 0.0]

In [25]:
0.5 * ((x_cur - x_prev) / 2 + (x_next - x_prev) / 2)

array([-0.75,  0.25,  2.  ,  0.  ])

In [21]:
x_cur

array([ 0, -1,  2,  4])

In [10]:
slope

array([-1, -1,  3,  2, -4])

In [35]:
np.zeros(len(x))

array([0., 0., 0., 0., 0., 0.])

In [ ]:
def derivative_ts(x):
    derivative = np.zeros(len(x))